services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db
      MYSQL_USER: osos
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - mysql
